### ISSUE TITLE
Is it possible / request to be able to customize the bottom row ( 123, space, return) like the rest in the .json?

### ISSUE THREAD

**Issue by waelsaad** [divvun/giellakbd-ios#100]
<img width="401" alt="Screen Shot 2020-01-24 at 10 58 29 pm" src="https://user-images.githubusercontent.com/4057766/73067845-cfab9d00-3efd-11ea-9eb1-96019b2d0c14.png">

This one is a very important one actually as I need to be able to insert couple of more buttons in the very bottom row (i.e 123, space, btn1, btn2, btn3, return).

Why is this row also not being controled or customized within the .json or  there is a way and I am just missing something? Thanks

**Comment by snomos** [comment]
What kind of buttons would you need to add? There are good reasons for keeping the bottom row as it is, but there might of course be good reasons for changing it as well :)

Anyway, this is not something we will prioritise to add now, it will require some substantial changes to kbdgen and other pieces of the build chain. But given a reasonable use case, it can be considered in a future update. And you can always send us a PR :)

**Comment by waelsaad** [comment]
Oh man :] I am still learning about this library this will be one heck of a PR for me :), its actually pretty essential for this language as it has like around 33+ alphabets and I'll need to customize the bottom row for it.

I am not just saying this  honestly because I obviously need that functionality but I am very suprised for this limitation!. I mean we have every row including spacing to be customazible except the last row!. it doesn't make sense to me. :]

**Comment by waelsaad** [comment]
Its going to be pretty much a killer for me to keep going without it. I am hoping you guys will actually have sometime to consider it.

**Comment by snomos** [comment]
We do as well have languages with substantially more letters than English, [Skolt Sámi](https://github.com/giellalt/keyboard-smi/blob/master/smi.kbdgen/layouts/sms.yaml) has 39 letters + two additional alphabetic symbols. What we do is that we add a *fourth* row on the top (or fifth if you also count the space bar row). With four rows, each at a maximum of 12 letters (more will be too cramped for the users) you will have the possibility of 44 letters directly accessible. In addition to that you can put less frequent letters on the long-press popup, where each popup can have at least 12 (the maximum we are using), possibly as much as 20 (not tested though!).

I hope that the combination of these two suggestions (an extra top row and long-press popup) will be enough for meeting the needs of your language :)

**Comment by waelsaad** [comment]
Thank you for your suggestions :).

1- Could you please send me a sample KeyboardDefinitions.json where it has an additional row so I can see what it might look like.

At the end of the day I know I will end up trying to find a way to hack the code to just add the 2 or 3 additional buttons  as I can imagine when the user is switching between the native keyboard and the custom one it will look like a bit of jumping in terms of height.

2- I know this will not sound right as a potential solution but I would just like to try it out anyway, would you please give me a hint where to look in the code if I was to do some kind of a hack to inject 2 or 3 buttons as I am still getting familiar with the code. I understand ultimately it needs to be in the .json file and that's what I might consider doing in the future but once I get a good understanding of how its implemented.

Thank you @snomos

**Comment by snomos** [comment]
I have never worked with the json code as it is generated, I only work with the yaml code linked to above (I am a linguist and heading the project, not a programmer doing the hard stuff). But I guess @bbqsrc can give you the relevant hints.

Thanks for your interest in our code.

**Comment by waelsaad** [comment]
No worries, Thank you, I am getting closer to understanding it and great job.

**Comment by bbqsrc** [comment]
@waelsaad so you don't need to use the JSON files. Those are an artefact from kbdgen, which are then parsed into `KeyboardDefinition` structs. You could just create this struct yourself.

Right now, the bottom row is always handled by the class `SystemKeys`.

My suggestion, if you want to make a contribution that allows you to manually handle the system keys row yourself, is create a new `init` function on KeyboardDefinition for hand-crafted layouts. :smile:

**Comment by waelsaad** [comment]
Thank you Brendan 👍

**Comment by bbqsrc** [comment]
In future iterations it likely will be, but we had to start somewhere. 😄
