### ISSUE TITLE
Add VoiceOver support

### ISSUE THREAD

**Issue by dylanhand** [divvun/giellakbd-ios#103]
- [x] Selecting shift key should cause VoiceOver to say "Shift" in native language
- [x] Selecting delete key should cause VoiceOver to say "Delete" in native language
- [x] "123" should say "more, numbers" in native language instead of "one hundred and twenty three"
- [x] Globe button should say "next keyboard" in native language instead of "button"

**Comment by dylanhand** [comment]
Note that these have, so far, only been localized into English. 

Localization files have been added, so only the localized strings for each supported language need be added.

**Comment by bbqsrc** [comment]
@snomos you can grab the code and modify the strings files :)

**Comment by snomos** [comment]
Already on it 🙂

**Comment by snomos** [comment]
Done, sme from @albbas, fin from Google :) (but checked, seemed ok).

**Comment by dylanhand** [comment]
Thanks for adding the translations @snomos :)

I noticed there aren't commas between words for phrases such as "more, letter" - was this intentional?

Eg:
```
"accessibility.moreLetters" = "lisää kirjaimia";`
```

The system, at least in English, pauses so that these read more like "more: letters", "more: symbols", and so on.

Let me know if this wasn't intentional and I can add the spaces.

**Comment by snomos** [comment]
I have now updated the strings to what I think is the best for VoiceOver performance. I used colon instead of comma, since that both should provide the same short break, and makes the semantics of the strings clearer. I didn't touch English though.

**Comment by dylanhand** [comment]
Thanks @snomos - I'll double check that the colon still behaves as expected with VoiceOver, and if so, will change the English ones to colons as I agree it's more clear.

**Comment by dylanhand** [comment]
I tested the new strings using a colon and they work the same. I've update the English strings to match.
