### ISSUE TITLE
Suggestions hard to hit on iPad 9.7"

### ISSUE THREAD

**Issue by snomos** [divvun/giellakbd-ios#104]
It seems that one has to hit the suggestion text precisely to get the keyboard to pick up the touch. This makes it hard and slow to use the speller suggestions.

The cause is probably that only the text is a target for the touch detection area. I suggest that the whole area between the separator bars, and the full height of the suggestion area, is responding to touches. Probably with a small margin to the top row buttons to avoid mistypes, but otherwise the full area.

**Comment by dylanhand** [comment]
This affected all devices.
