### ISSUE TITLE
iPad long-press popup different from Apple's

### ISSUE THREAD

**Issue by snomos** [divvun/giellakbd-ios#105]
By Apple, the long-press popups are *different* on iPads compared to iPhones. See screenshots below. Whether we want to care about this or not is another question, but at least it needs consideration, since an overall goal is consistency with Apple's keyboards.

E-popup, Divvun:
<img width="768" alt="E-popup-Divvun" src="https://user-images.githubusercontent.com/1255285/73166382-68107000-40fe-11ea-9f01-366c4fcbaa6e.png">

A-popup, Divvun:
<img width="768" alt="A-popup-Divvun" src="https://user-images.githubusercontent.com/1255285/73166410-75c5f580-40fe-11ea-94d9-9f9c8b581371.png">

E-popup, Apple:
<img width="768" alt="E-popup-Apple" src="https://user-images.githubusercontent.com/1255285/73166495-9db55900-40fe-11ea-9b27-62a636f89afe.png">

A-popup, Apple:
<img width="768" alt="A-popup-Apple" src="https://user-images.githubusercontent.com/1255285/73166470-8ecea680-40fe-11ea-8886-ca33f7c9f124.png">

**Comment by bbqsrc** [comment]
It isn't much work (there's an if statement determining if we do the floating one vs non-floating) but we'll prioritise the other stuff first.

**Comment by snomos** [comment]
Also note how the pressed base key ('*E*' and '*A*') have a deeper shadow on Apple's keyboard.

**Comment by snomos** [comment]
> It isn't much work (there's an if statement determining if we do the floating one vs non-floating) but we'll prioritise the other stuff first.

Sounds good.

**Comment by bbqsrc** [comment]
No shadow for you!

**Comment by snomos** [comment]
> Also note how the pressed base key ('_E_' and '_A_' in the screenshots above) have a deeper shadow on Apple's keyboard.

And a raised letter.

**Comment by bbqsrc** [comment]
Will revisit during the iOS 14 beta period.

**Comment by snomos** [comment]
>  Whether we want to care about this or not is another question, …

We don't, it is good as it is. Closing.
