### ISSUE TITLE
Don't auto-shift after colon

### ISSUE THREAD

**Issue by dylanhand** [divvun/giellakbd-ios#115]
To be consistent with the native keyboards, shift mode should not be enabled by the system after typing a colon ':'

It's possible there are other punctuation characters that also auto-shift and should not.

@snomos can you confirm this is not desired behavior for these languages?

**Comment by snomos** [comment]
@dylanhand I can confirm that it is not the desired behavior for these languages.

One can imagine that for some punctuation this is different between languages, so ideally this should be configurable in the layout yaml file or somesuch. But such configurability is a future feature request. For now it is good enough to just do it consistently for all languages for the same set of punctuation chars.

**Comment by dylanhand** [comment]
Thanks for the clarification. We’ve added it as a feature to be addressed
in the future.

**Comment by bbqsrc** [comment]
Fixed
