### ISSUE TITLE
Replace Pods with Swift Package Manager - Enhancement

### ISSUE THREAD

**Issue by waelsaad** [divvun/giellakbd-ios#121]
Pods have served their time and now they are horrible in comparison to others, Carthage is 10 x better than pods but now there is Apple's native Swift Package Manager. It should be straight forward to replace.

It would be nice to get rid of all these pod scripts in the Build Phases and in the folder structure.

Thanks

**Comment by bbqsrc** [comment]
Swift Package Manager does not support non-Swift dependencies so cannot be used with this project, and in the same grain, there are tradeoffs made between Carthage and Cocoapods that resulted in Cocoapods being chosen.

I can appreciate the desire for a simpler project model, but it is not a priority for this project. I hope you understand. 🙂
