### ISSUE TITLE
Locale/language list seems hardcoded

### ISSUE THREAD

**Issue by snomos** [divvun/giellakbd-ios#13]
It contains languages not available in the app (like Finnish and Swedish), and it does not contain locales available to the app, like Norw. Nynorsk:

![image](https://user-images.githubusercontent.com/1255285/40679164-1de61aae-638b-11e8-82ba-e356192c3aed.png)

Cf [the code](https://github.com/divvun/giellakbd-ios/tree/master/HostingApp), which contains the following locales: ``Base, nb, nn, se``.

**Comment by snomos** [comment]
This is what it looks like when selecting the non-existing locale ``fi``:

![image](https://user-images.githubusercontent.com/1255285/40679400-ae19bfcc-638b-11e8-937c-58cdabb35f02.png)

**Comment by snomos** [comment]
What is strange to me, is that the name of the app is nevertheless localised to e.g. Finnish:

![img_1038](https://user-images.githubusercontent.com/1255285/40706396-56fcf4dc-63f6-11e8-856f-e77a61f46a49.PNG)

**Comment by bbqsrc** [comment]
It's a caching bug in Xcode. The locale list is not hardcoded. Delete `DerivedData` as usual.
