### ISSUE TITLE
Keyboard covers parts of the non-keyboard area

### ISSUE THREAD

**Issue by snomos** [divvun/giellakbd-ios#14]
See screenshots:

![img_1039](https://user-images.githubusercontent.com/1255285/40708444-22f42c36-63fc-11e8-9072-4b16ea4de89e.PNG)

![img_1040](https://user-images.githubusercontent.com/1255285/40708465-2f7cdab6-63fc-11e8-95be-c58f7f03229f.PNG)

**Comment by bbqsrc** [comment]
This is meant to be impossible, as the height is entirely handled by the OS... lol

**Comment by snomos** [comment]
Fixed in the new implementation (if not earlier).
