### ISSUE TITLE
Regression: no upper case after full stop

### ISSUE THREAD

**Issue by snomos** [divvun/giellakbd-ios#141]
This is a regression in version 2.2.6, build 135, it used to work. To repeat:

1. Type a word
1. double tap space bar to get a full stop and space

Result: keyboard is in lower case state (see screenshot)

Expected: keyboard in upper case state.

![b0Px9AMLTveEOsXajekPrQ_thumb_1c6c9](https://user-images.githubusercontent.com/1255285/76110462-ddfdd600-5fde-11ea-878a-a4ccbc0e3381.jpg)

**Comment by bbqsrc** [comment]
Add a regression test for this one.

**Comment by dylanhand** [comment]
@bbqsrc this happened after we changed the `CursorContext` to support the User Dictionary.

Two possible solutions:
1. Change `CursorContext` to include punctuation like it did before. This will require some thought so we don't mess up UserDictionary
2. Manually get the context outside of the `CursorContext` to look for punctuation in this particular case (seems like then we're doing the work twice)
