### ISSUE TITLE
Space key has no label when in symbol/punctuation/digit mode

### ISSUE THREAD

**Issue by snomos** [divvun/giellakbd-ios#15]
See attached screenshot:

![img_1041](https://user-images.githubusercontent.com/1255285/40708864-336e39d4-63fd-11e8-9501-1d99dacfcadc.jpg)

**Comment by snomos** [comment]
On Apple's keyboards the space key is labelled all the time.

**Comment by albbas** [comment]
Another user reported that they have to press the space key twice to make a space and activate the space button, as well.

This is on an iPhone5, iOS12
![image-11](https://user-images.githubusercontent.com/75695/45679731-8002d780-bb39-11e8-82eb-ec7591d6d14c.jpg)

**Comment by snomos** [comment]
Closing this was not intended :)

**Comment by snomos** [comment]
Fixed in 2.1.0 (18) (the new codebase).
