### ISSUE TITLE
Keyboard uses iPad layout in floating mode

### ISSUE THREAD

**Issue by snomos** [divvun/giellakbd-ios#154]
To repeat:

1. start with a native keyboard
1. press and hold the keyboard button
1. select Floating/Flytande etc - the keyboard is now detached, and placed in a floating window; it uses what looks like the native iPhone keyboard layout (NOT the iPad layout)
1. move the native keyboard to whereever you want
1. press the globe button, and switch to a Sámi keyboard

Notice how the layout is still the iPad layout, squeezed inside the mobile screen size window. See attached screen shot.

This is possibly the same bug as #126.

![IMG_BFBC87DD60E6-1](https://user-images.githubusercontent.com/1255285/78532671-4fa08e00-77f0-11ea-96d2-dd2c538a69aa.jpeg)

iPad Pro 9.7", iOS 13.3.1.

**Comment by bbqsrc** [comment]
Definitely looks to be exactly the same as #126. As previously described, we _already_ have all the code we could work out to detect what mode the keyboard should be in, so if it's not declaring that it should be in iOS mode there, then there's not much we can really do, other than doing hacks that detect the _width_, which I would be wary of right now.

**Comment by snomos** [comment]
Gboard handles this situation fine:

![IMG_1002](https://user-images.githubusercontent.com/1255285/78536058-e02d9d00-77f5-11ea-95f4-2435f0927306.PNG)

Compare with the keyboard in #153, and you'll notice this is not the iPad layout.
