### ISSUE TITLE
User dictionary not populated when using keyboard

### ISSUE THREAD

**Issue by snomos** [divvun/giellakbd-ios#168]
The following pattern of actions result in user dictionary entries *on Android*:

- type a word first time (no entry)
- a second time (no entry, but probably candidate)
- a third time - entry

On iOS (iPad, app version 2.99.7) nothing happens irrespective of how often a word is typed.

Tested on Android using smj_NO and "jå", tested on iOS using SRS and "ja".

**Comment by dylanhand** [comment]
This was because the ENABLE_USER_DICTIONARY compiler flag wasn't added to the Keyboard Extension.
