### ISSUE TITLE
Rust dependency fail

### ISSUE THREAD

**Issue by nikans** [divvun/giellakbd-ios#169]
I'm not acquainted with Rust and Cargo. Getting a dependency error when trying to build a project:

<img width="814" alt="Screenshot 2020-06-30 at 21 54 58" src="https://user-images.githubusercontent.com/1039100/86165841-8ef32800-bb1c-11ea-91da-0be24b9f4626.png">

Help appreciated.

**Comment by bbqsrc** [comment]
@nikans having a look, give me a few minutes.

**Comment by bbqsrc** [comment]
@nikans update your pods, it should work now.

**Comment by nikans** [comment]
Success. Thank you for such a quick fix )
