### ISSUE TITLE
Shift key not consistent with Apple keyboards

### ISSUE THREAD

**Issue by snomos** [divvun/giellakbd-ios#17]
The shift key in the Sámi keyboards is always black/filled, as opposed to the Apple keyboards, where the lower-cased state uses a non-filled up arrow. See the attached screenshots for comparison. To not confuse users, it should be the same as for the Apple keyboards.
![img_1417](https://user-images.githubusercontent.com/1255285/42039563-faa60eda-7aed-11e8-9d0e-d148e6ffc06e.jpg)
![img_1419](https://user-images.githubusercontent.com/1255285/42039584-0821ae8e-7aee-11e8-8465-53c8c86d7f0a.jpg)
![img_1418](https://user-images.githubusercontent.com/1255285/42039577-03f42f4e-7aee-11e8-87e9-d07ab7517aea.jpg)
![img_1420](https://user-images.githubusercontent.com/1255285/42039594-0b67c498-7aee-11e8-8ee2-162c576ed942.jpg)

**Comment by snomos** [comment]
In 2.1.0 (18) (the new codebase) the shift key is now always hollow, like the unshifted Apple key.

**Comment by bbqsrc** [comment]
Shifted state is still not perfect in the rewrite.
