### ISSUE TITLE
User dictionary language list is gone

### ISSUE THREAD

**Issue by snomos** [divvun/giellakbd-ios#179]
In the latest builds.

**Comment by bbqsrc** [comment]
Xcode 12 must have broken environment variable handling ... sigh

**Comment by snomos** [comment]
![RPReplay_Final1603973048](https://user-images.githubusercontent.com/1255285/97572453-ed5be480-19f0-11eb-83f7-f1a5aa34955d.gif)

**Comment by bbqsrc** [comment]
Fixed
