### ISSUE TITLE
IPhone X / iOS 12.0.1

### ISSUE THREAD

**Issue by albbas** [divvun/giellakbd-ios#18]
After an update to a new iOS version, the keyboard has been slowed down. 

The key-buttons react either a couple of seconds after being pressed, or have to be prodded a couple of times before they react.

Other keyboards and apps act as they should.

Removing and reinstalling the app did not improve the situation.

**Comment by snomos** [comment]
More reports along the same line: after update to iOS 12, smj keyboard is very slow or not accessible at all. It seems to be related to big-screen phones, as the one reported to me is an iPhone 6 Plus, whereas the keyboard is working fine on my regular iPhone 6.

**Comment by bbqsrc** [comment]
The issue seems to be that on the largest phone sizes the hitboxes on the keys are too small, so it's possible to actually tap _between_ the keys. @villepetersson is taking a look now.

**Comment by snomos** [comment]
Fixed in 2.1.0 (18) (the new codebase) if not earlier.
