### ISSUE TITLE
Ordforslag på samisk tastatur fungerer ikke på Ipad ios 14.6

### ISSUE THREAD

**Issue by stoneman2x** [divvun/giellakbd-ios#189]
![IMG_20210615_102204](https://user-images.githubusercontent.com/66414661/122020923-7d566f00-cdc5-11eb-8af0-833afa352345.jpg)
Normalt skal det komme opp ordforslag nederst på linja.

**Comment by stoneman2x** [comment]
Det er mulig at dette henger opp imot innstillinger inne i Intune løsninga siden dette fungerer på "private" ipads

**Comment by snomos** [comment]
> Det er mulig at dette henger opp imot innstillinger inne i Intune løsninga siden dette fungerer på "private" ipads

Eg vil tru at dette er kjerna i problemet. Det samiske tastaturet, inkl. stavekontrollen, fungerer på OS-nivå og burde fungera over alt. Men enkelte program kan overkøyra OS-oppsettet, og det har vi ingen kontroll over.

**Comment by snomos** [comment]
Eg avsluttar denne saka, sidan vi ikkje kan gjera noko med henne. Det ville vera bra om du melder problemet til Adobe og folka bak InTune, @stoneman2x 🙂 . Om dei har spørsmål, eller treng meir info, kan du visa til denne saka og be dei ta kontakt med oss.
