### ISSUE TITLE
Iphone 13 has two "globe" icons when using divvun keyboard

### ISSUE THREAD

**Issue by ZoeyR** [divvun/giellakbd-ios#198]
There are two "globe" icons for switching keyboard language when a Divvun keyboard is active on the new Iphone 13

iOS Version: 15.0.2
Divvun Version: v3.1.1

![Image from iOS](https://user-images.githubusercontent.com/8010244/140057943-18d6524b-c94c-442b-896c-2014751a9c9c.png)

**Comment by snomos** [comment]
Fixed in 7e35a6d2cd62f113f1fd5a9c8b1a9ed7d1cd1a2d
