### ISSUE TITLE
Spell checker stopped working 0.2.1

### ISSUE THREAD

**Issue by ilm024** [divvun/giellakbd-ios#203]
I've been testing Divvun Dev v0.2.1 since friday,  today the spell checker suddently stopped working.

![IMG_5989](https://user-images.githubusercontent.com/65161699/172553259-4b284a3b-a430-4dec-9dfa-3a85d73a8ad6.PNG)

**Comment by snomos** [comment]
Det skal vera fiksa for ei god stund sidan.
