### ISSUE TITLE
Incorrect detection of crk-SRO-circumflex keyboard on iPad mini

### ISSUE THREAD

**Issue by aarppe** [divvun/giellakbd-ios#208]
On a new iPad mini, there are three errors concerning the keyboard that is made available for crk, with the predictive speller in SRO using circumflexes.

- [x] the keyboard follows the 12" iPad layout (with four rows), instead of the 9" iPad format (with three rows). For an iPad mini screen, the 9" iPad layout would be much more fitting.
- [x] the keyboad layout (using the 12" iPad format) is missing the globe key (to the left of the space-bar), which means that one cannot swap the keyboard to any other one, after one has selected the crk-SRO-circumflex one.
- [ ] in the implementation of the 12" iPad layout, the second, q-p row, is aligned all too much to the right edge; instead, it should be more centrally positioned.

Visual examples of the above glitches can be observed here:

![kanstohtat_A2C29EB8-F21B-44BF-AA94-80F20D291F27](https://user-images.githubusercontent.com/15003407/192077837-062ca262-754a-495c-98c9-1f75897ccd4d.png)

This issue is also covered here: https://github.com/giellalt/keyboard-crk/issues/16 and https://github.com/giellalt/keyboard-crk/issues/9

FYI: @bbqsrc

**Comment by aarppe** [comment]
This behavior has also been observed on some Android phones, but not on my Android tablet (a new Lenovo). The complication is that one gets stuck with the crk keyboard, and the only way to access other keyboards is to uninstall this one - which is a less desirable feature.

**Comment by dylanhand** [comment]
This should now be fixed as of this commit: https://github.com/divvun/giellakbd-ios/commit/6a0a4233f7d9aac444c8579938d4a27837cc3ccc

I tested using what I believe was a crk-SRO keyboard but I'm not sure what circumflex is. 

The latest Divvun Dev Keyboards build in TestFlight has the fix (should be fixed as of version 0.2.6 (129))

**Comment by aarppe** [comment]
Yes, it looks like this is fixed, in terms of the keyboard matching the iPad Mini tablet size, cf.

<img width="580" alt="image" src="https://github.com/divvun/giellakbd-ios/assets/15003407/eeb89cb2-03ee-41ab-b62c-a6d772856bae">

**Comment by snomos** [comment]
Yes, all items in the original message have been fixed, except for the layout adjustments of the 12" iPad layout. Layout improvements do not belong in this repo though, so should be filed as a separate issue in [keyboard-crk](https://github.com/giellalt/keyboard-crk) (now filed as https://github.com/giellalt/keyboard-crk/issues/18).
