### ISSUE TITLE
XCode Build Instructions

### ISSUE THREAD

**Issue by superstormage** [divvun/giellakbd-ios#215]
So far I have downloaded the repo and tried to build either HostingApp or BaseKeyboard all failed with some dependency related errors. I did went through `pod install` and even try to manually kicking off build for Pods-BaseKeyboard. They all ended up with some dependency could not find/symbol not find. 
Not clear to me how this one suppose to work

**Comment by dylanhand** [comment]
@superstormage the changes I made can be found on this branch: 
https://github.com/divvun/giellakbd-ios/tree/bugs_fixes/letter-popup

Will be merged soon, but in case you try again before it is.

**Comment by snomos** [comment]
No further feedback from OP. Assuming fixed. Closing.
