### ISSUE TITLE
Fix iOS builds

### ISSUE THREAD

**Issue by snomos** [divvun/giellakbd-ios#219]
The builds are broken, cf e.g. https://github.com/divvun/divvun-keyboard/runs/14209012515

**Comment by dylanhand** [comment]
Both should be fixed now.

**Comment by snomos** [comment]
The CI build has been fixed a while now, but what is the *other* issue that should have been fixed?

**Comment by dylanhand** [comment]
@snomos I meant that both the Android and iOS builds were fixed - sorry that was unclear :)

**Comment by snomos** [comment]
No problem. I close this then.
