### ISSUE TITLE
Height of keyboard effectively doubles before settling on natural height upon loading

### ISSUE THREAD

**Issue by bbqsrc** [divvun/giellakbd-ios#28]
When opening the keyboard, the keyboard tends to be double its expected height for less than a second. This is a jarring experience and should be fixed if possible.

**Comment by bbqsrc** [comment]
It shouldn't "double" anymore but there's still something wrong here.

**Comment by dylanhand** [comment]
I've occasionally seen this too but I'm not sure it's fixable. After playing with other keyboards it appears they also glitch. Google's Gboard for instance flashes white before settling on dark when in dark mode. It appears our size glitch happens only sometimes on first load of the keyboard. Once it's in memory it doesn't seem to happen.

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/431529/71889836-4d705a00-3143-11ea-80f2-3a191b49677f.gif)

I've noticed that there are conflicting constraint warnings that appear when the keyboard is loaded for the first time. Fixing these *might* help the problem.

**Comment by dylanhand** [comment]
Was able to better reproduce this on a larger physical device (iPhone 7 Plus).

It's possible that this has something to do with #71

**Comment by dylanhand** [comment]
To document what's been fixed, attached are videos of the keyboard initializing before and after the change. 

Note that this change does not fix the issue where the keyboard height is momentarily shorter than expected on large devices.

iPhone 5 before fix:
![iphone5-before](https://user-images.githubusercontent.com/431529/72975977-0389a400-3dd2-11ea-9080-90e98c1f3812.gif)

iPhone 5 after fix:
![iphone5-after](https://user-images.githubusercontent.com/431529/72976001-0be1df00-3dd2-11ea-8c92-f30f4b3b698e.gif)


iPhone 7 Plus before fix:
![iphone7plus-before](https://user-images.githubusercontent.com/431529/72976018-11d7c000-3dd2-11ea-83e5-bfe5f02a0138.gif)


iPhone 7 Plus after fix:
![iphone7plus-after](https://user-images.githubusercontent.com/431529/72976036-17cda100-3dd2-11ea-899f-d5e40d6f7b76.gif)
