### ISSUE TITLE
Long press area not selectable on second row and beyond

### ISSUE THREAD

**Issue by bbqsrc** [divvun/giellakbd-ios#30]
When there are more than 4 long press items on iPhone, or 6 items on iPad, the long press popover should be 2 rows.

We have the logic for this but it is currently disabled as it seems there an issue with the touch coordinates interfering with the constraints.

**Comment by bbqsrc** [comment]
Fixed

**Comment by bbqsrc** [comment]
We lied, it has regressed.

**Comment by dylanhand** [comment]
Fixed.
