### ISSUE TITLE
Capitalisation bug after speller

### ISSUE THREAD

**Issue by snomos** [divvun/giellakbd-ios#36]
To reproduce:

* switch to North Sámi keyboard
* type return/newline
* type the following letters: m a i d
* you should get as one of the suggestions ‘Máid’, select that one

Note how the keyboard now is in uppercase state. It should be in lowercase, as the next character is not the first in the paragraph.

**Comment by bbqsrc** [comment]
Cannot reproduce, try with today's build.

**Comment by bbqsrc** [comment]
Fixed
