### ISSUE TITLE
KeyOverlay is shifted below expected location

### ISSUE THREAD

**Issue by dylanhand** [divvun/giellakbd-ios#55]
![Simulator_Screen_Shot_-_iPhone_11_Pro_-_2020-01-07_at_15_56_11](https://user-images.githubusercontent.com/431529/71904581-b0271d00-3166-11ea-8d41-6ae4019245b4.png)

Expected:
![Simulator Screen Shot - iPhone 11 Pro - 2020-01-07 at 15 56 23](https://user-images.githubusercontent.com/431529/71904591-b5846780-3166-11ea-97a1-194a8e0d6d8b.png)

**Comment by snomos** [comment]
Hi @dylanhand ! Isn't it so that the whole popover area is shifted downwards? It is not only the bottom, but all of it as far as I can see.

**Comment by dylanhand** [comment]
Hi @snomos ! You’re right, it looks like the whole thing is shifted down. Is this intentional? Assuming it’s not, I’ll shift it back up.

**Comment by snomos** [comment]
I think it is safe to assume it is _not_ intentional - just shift it back up :)
