### ISSUE TITLE
Globe key menu contains Keyboards settings but not left or right shifted keyboard options

### ISSUE THREAD

**Issue by snomos** [divvun/giellakbd-ios#6]
In the simulator (using an iPhone 6s running 11.2 as the target device), the keyboard menu in the keyboard app does not provide the same functionality as Apple's keyboards' globe menu:

- both have the Keyboard Settings... entry on top
- Apple's has three options at the bottom for a left- or right-shifted keyboard or a standard one - this does not appear in the Sami keyboards
- Apple's is attached to the globe key, ie it looks like a pop-up from the key, whereas the one in the sami keyboard app is a floating list of entries, and the globe key is not highlighted as being pressed - looks weird

See attached screenshots.

<img width="559" alt="skarmavbild 2018-04-17 kl 11 40 19" src="https://user-images.githubusercontent.com/1255285/38858592-d01d8ff4-4234-11e8-9bf2-ddcbf883ec7c.png">

<img width="559" alt="skarmavbild 2018-04-17 kl 11 40 32" src="https://user-images.githubusercontent.com/1255285/38858636-eb385bfc-4234-11e8-83a6-f51fa030c79d.png">

**Comment by bbqsrc** [comment]
The menu provided is the only menu available to third-party keyboards using Apple's official keyboard API.

As we cannot draw on that layer (it is considered fully on top of the app) we cannot even make the globe button look like it is touching the menu without the shadow making it look strange.

**Comment by snomos** [comment]
Ok. I'll close as a WONTFIX then.
