### ISSUE TITLE
Top row long-press popup distorted

### ISSUE THREAD

**Issue by snomos** [divvun/giellakbd-ios#60]
### Dark mode

Divvun middle row:
![IMG_7708](https://user-images.githubusercontent.com/1255285/72155140-1ad09680-33bb-11ea-81d7-5e7a23d09d6b.jpeg)

Divvun top row:
![IMG_7704](https://user-images.githubusercontent.com/1255285/72155233-5cf9d800-33bb-11ea-84ae-32425cfdf0fa.jpeg)

Apple middle row:
![IMG_7714](https://user-images.githubusercontent.com/1255285/72155262-68e59a00-33bb-11ea-95c1-066768f93209.jpeg)

Apple top row:
![IMG_7707](https://user-images.githubusercontent.com/1255285/72155291-7a2ea680-33bb-11ea-979f-d4f01b12cb0e.jpeg)

### Light mode

Note the lack of shaddow at the bottom of the Divvun popups, in addition to the distorted top row popup:

Divvun middle row:
![IMG_7713](https://user-images.githubusercontent.com/1255285/72155444-d5f92f80-33bb-11ea-9f77-6c4f01a23a0f.jpeg)

Divvun top row:
![IMG_7712](https://user-images.githubusercontent.com/1255285/72155455-dabde380-33bb-11ea-9d73-6a0ffb2893f4.jpeg)

Apple middle row:
![IMG_7711](https://user-images.githubusercontent.com/1255285/72155537-0640ce00-33bc-11ea-9248-6c4515abc31c.jpeg)

Apple top row:
![IMG_7710](https://user-images.githubusercontent.com/1255285/72155489-e6a9a580-33bb-11ea-8d0c-be7518342fc5.jpeg)

I assume we don't have the luxury of extening the popup outside the keyboard area, so we need to look for another solution. I would suggest we reduce it to one row only, instead of two. That should leave enough room for decent rendering. It might then be necessary to add horisontal scrolling when there are a lot of long-press letters, especially on small screens. Additional letters should be indicated with `…` at the end where more letters are found.

Tested with version 2.2.2, build 107.

**Comment by snomos** [comment]
Eample of Divvun one-row long-press popup for the top keyboard row:

![IMG_7715](https://user-images.githubusercontent.com/1255285/72156011-12795b00-33bd-11ea-9828-4a63cd3b64d8.jpeg)

This one seems fine, so something similar to this should be good.

**Comment by dylanhand** [comment]
Hi @snomos - you're right, I don't believe we can extend the popover outside of the keyboard view bounds.

To clarify, is it now preferred to display popup keys in a single row? My understanding was that a two-row long press popup was a requirement. If a single row is now preferred, I think it's best to be consistent and display all popups that way. Let me know what you think.

**Comment by snomos** [comment]
Correct, this is how it is written in the contract specification:

> long-press pop-ups should render as Apple’s, with the additional feature that the pop-up should render in two or more rows if the number of letters is too long to fit on one line (this is how our keyboard works on Android).

Now, if it turns out that two rows are not feasible, desirable or possible in some cases, we need to rethink this requirement. I would like feedback from @bbqsrc on this.

And yes, I agree that the long-press popup should be displayed consistently in all cases 🙂 

How would you solve this issue, given we want to keep the two-row implementation?

**Comment by bbqsrc** [comment]
Two row popup isn't the problem, the bezier curve code is broken when the constraints do not allow the popup longpress area to draw beyond the top.

It's fine is it has to be confined to the drawable area, but the popup path should connect problem and not contort into itself.

**Comment by snomos** [comment]
Yes, the bezier curve code is broken and should be fixed, but the question is still: what is actually best for the users? Now that we have had a two-row popup for a while, I am not so sure anymore that what we specified in the contract (two rows) is the best solution. I am not saying that we should switch to a one-row popup, I am just asking the question, and would like some discussion on this. I will try to gather feedback from iphone users (Android users don't really qualify ;) ) to see if there are strong opinions in one direction or the other. And in any case, this is not something that needs settling in the near future.

**Comment by dylanhand** [comment]
A few considerations regarding the popup:
- Though ideally we'd be able to display the popup above the keyboard area, I didn't feel that the popup being drawn slightly lower was *that* bad a user experience. I think it's still usable. Curious your thoughts here.
- One option would be to raise the threshold before long press characters are split into two rows. In other words, instead of splitting a list of 8 characters into two rows of 4, we could only do so if there are more than 10 or so characters (if possible - this might require making keys smaller if more than 9). That way the keyboard stays more consistent with Apple's (see below screenshot) until it absolutely must split lines. This would at least fix the 'i' and 'e' characters on the smi keyboard. The 'o' however may require splitting lines as it has 12 characters.
- A one-row popup that supports scrolling side-to-side I think could become cumbersome very quickly. The user would have to long press, then slide to the side, then once their character was revealed, selected it in the list. A two-row long press popup is better in my opinion because it provides instant access to all characters.
- We can buy ourselves a few pixels by making our autocorrect banner taller. When testing, I noticed that our keyboard is slightly shorter than Apple's, and from memory believe it was because their autocorrect banner was taller. If necessary, we could make our keyboard even taller than Apple's to better accommodate top-row long press popups, though we'll of course want to be considerate of the user's screen real estate.

The way I think makes most sense to fix this is to keep the two row popup, but consider raising the threshold so it's displayed only when absolutely necessary.

Here's a screenshot of Apple's US keyboard where 9 characters are displayed in a single row popup:
![IMG_5977](https://user-images.githubusercontent.com/431529/72240857-99108100-35e5-11ea-91dd-9365008a52ea.PNG)

**Comment by snomos** [comment]
I agree with your line of reasoning:

* having instant access to all popup letters is good, so scrap the scrolling one-row idea
* increase the height of the autocorrect banner by a few pixels, to make it as tall as Apple's
* higher threshold before triggering two-row layout, possibly dynamic according to screen size, so that two rows would only be used when absolutely required — it should then never be used in horizontal mode

I think it is necessary to make a version with these changes in place before we discuss the popup further. Seeing and testing will make it clear whether we need more adjustments :)

**Comment by dylanhand** [comment]
Sounds good - I'll make a version with these changes and we can discuss from there :)

**Comment by dylanhand** [comment]
The path drawing bug is fixed. 

Note that light mode shadow is **not** fixed - that's now in a separate issue here: #62

**Comment by dylanhand** [comment]
FYI @snomos - I'm nearly done with these changes. I got hung up with the banner size because it turns out it's different for each device size. Planning to have a build out by lunchtime tomorrow :)

>     * having instant access to all popup letters is good, so scrap the scrolling one-row idea
> 
>     * increase the height of the autocorrect banner by a few pixels, to make it as tall as Apple's
> 
>     * higher threshold before triggering two-row layout, possibly dynamic according to screen size, so that two rows would only be used when absolutely required — it should then never be used in horizontal mode
> 
> 
> I think it is necessary to make a version with these changes in place before we discuss the popup further. Seeing and testing will make it clear whether we need more adjustments :)

**Comment by snomos** [comment]
> FYI @snomos - I'm nearly done with these changes. I got hung up with the banner size because it turns out it's different for each device size. Planning to have a build out by lunchtime tomorrow :)

Perfect!

**Comment by dylanhand** [comment]
New build is on its way (version 2.2.3 build 231). Here's what to expect:

1. 'O' is now the only top-row letter that has a two-row longpress popup. It was possible to safely fit 10 characters in a single row (even on iPhone SE).

![Simulator Screen Shot - iPhone 11 Pro - 2020-01-14 at 10 28 24](https://user-images.githubusercontent.com/431529/72331739-faedeb00-36b8-11ea-955a-1e3e7667cbe0.png)
![Simulator Screen Shot - iPhone 11 Pro - 2020-01-14 at 10 29 18](https://user-images.githubusercontent.com/431529/72331740-faedeb00-36b8-11ea-953d-f6f59ddb338b.png)

2. The keyboard height and banner height has been modified to match the native height on all iPhone models. In most cases, this gave us a few extra pixels to work with, which means the user has slightly more room in the event of a top-row two-row popup (note the extra area below the 'o' popup in the above screenshot).

3. The popup drawing code has been updated to be more robust and, most importantly, not glitch.

In my opinion these changes are an improvement over the last iteration. Let me know what you think and if you find any bugs :)

**Comment by snomos** [comment]
Looks good, I will test as soon as Testflight gives it to me.

One small detail: based on the screenshots, it looks like the popup "footer"  is now slightly *higher* than it should be, by a pixel or two — there's a strange shaddow at the bottom of it. It does not really matter, but it would probably make the popup stand out slightly better if corrected.

**Comment by snomos** [comment]
Got it from Testflight. This version seems good.

About that little detail: it seems that the whole popup is now shifted one or two pixels up, as also the buttons behind the popup list shows up a little just below the bottom line of the popup list. See attached screenshot:

![IMG_7720](https://user-images.githubusercontent.com/1255285/72334390-e8c67980-36c5-11ea-8902-167fde29625e.jpeg)

Compare with Apple's:
![IMG_7721](https://user-images.githubusercontent.com/1255285/72334418-f24fe180-36c5-11ea-87e0-c026bad6da99.jpeg)

Summary: good progress, we'll keep this popup implementation (ie two rows only if we exceed ten popup letters). One small visual glitch detected :)

**Comment by snomos** [comment]
The Apple English keyboard C popup is a better comparison:

![IMG_7722](https://user-images.githubusercontent.com/1255285/72334873-b49f8880-36c6-11ea-8382-17f6e39c83d8.jpeg)

**Comment by dylanhand** [comment]
Good eye - I saw that as well. It only happens in light mode, I'm guessing because in light mode there's a shadow below the keys. I'll make an issue for this.
