### ISSUE TITLE
Popup drawn improperly for long press keys in top row

### ISSUE THREAD

**Issue by dylanhand** [divvun/giellakbd-ios#61]
![Simulator_Screen_Shot_-_iPhone_11_Pro_-_2020-01-10_at_13_20_29](https://user-images.githubusercontent.com/431529/72155950-9418bb00-33b4-11ea-817d-e8305ec14666.png)

**Comment by snomos** [comment]
Hehe, we are filing duplicate bugs - see #60 😄

**Comment by dylanhand** [comment]
Hah, within minutes of each other. I'll close this one :)
