### ISSUE TITLE
Xcode warnings about flatMap

### ISSUE THREAD

**Issue by snomos** [divvun/giellakbd-ios#7]
In file `AppDelegate.swift`:

```
keyboards/smi/ios/ios-build/HostingApp/AppDelegate.swift:44:60: 'flatMap' is deprecated: Please use compactMap(_:) for the case where closure returns an optional value
```

**Comment by bbqsrc** [comment]
Language version is Swift 4.0, so this deprecation message is a false positive. Are you running Xcode 9.3?

**Comment by snomos** [comment]
Yes.

**Comment by bbqsrc** [comment]
Then this is a bug in Xcode 9.3 handling 4.0 code, and treating everything as 4.1. Swift 4.0 does not even include the `compactMap` method 😶

**Comment by bbqsrc** [comment]
This is safe to ignore as Swift will continue to support older versions of the language since 3.0, and as this codebase is earmarked for refactoring, we can revisit that if and when required.
