### ISSUE TITLE
Delete key often deletes two chars instead of one

### ISSUE THREAD

**Issue by snomos** [divvun/giellakbd-ios#77]
In my experience, the delete key often does double duty. You have to be very fast or light in your touch on the delete key to be sure it only deletes one char.

**Comment by dylanhand** [comment]
Fixed.

This has been enhanced to mimic native functionality. If the delete key is held down, there is a short pause before characters are more rapidly deleted.

This fix also changes the delete rate to be the same as native (faster, after initial pause).
