### ISSUE TITLE
Wrong background colour, shadow colour => flatter appearance

### ISSUE THREAD

**Issue by snomos** [divvun/giellakbd-ios#78]
The background colour is slightly different from Apples, and our shadow colour is slightly lighter. The net effect is that there is no visible shadow on the grey keys, like shift and symbol keys, and our keyboard looks flatter. Not a major thing, but if it is easy to fix, that would be great.

![IMG_7735](https://user-images.githubusercontent.com/1255285/72427747-175f5580-3795-11ea-9107-e05f73114503.jpeg)

**Comment by dylanhand** [comment]
- [ ] Fix background color to use same color as native keyboard
- [ ] Fix light keyboard to support transparency
- [ ] Fix key shadow color to match native keyboard (and make sure it shows up below gray buttons)
- [ ] Update gray button color (it looks like ours are darker than native)

**Comment by dylanhand** [comment]
Fixed.

Before (notice also no transparency):
![Simulator Screen Shot - iPhone 11 Pro - 2020-01-17 at 14 44 50](https://user-images.githubusercontent.com/431529/72616810-fa16bc80-3937-11ea-837f-77bfa1620fe4.png)

After:
![Simulator Screen Shot - iPhone 11 Pro - 2020-01-17 at 14 43 39](https://user-images.githubusercontent.com/431529/72616841-0864d880-3938-11ea-85a2-dcd02ad837d9.png)
