### ISSUE TITLE
Same suggestion twice

### ISSUE THREAD

**Issue by snomos** [divvun/giellakbd-ios#81]
Given input *Dette*, the speller suggests *Dette*. In addition, due to the changes lately to always suggest the input string to the left, there's another *Dette* even there (it works the same with lowercase *d*):

![IMG_7739](https://user-images.githubusercontent.com/1255285/72601803-c7ac9580-391e-11ea-8a5e-7fa488ceec40.jpeg)

There's no point in suggesting the same thing twice of course. The question is what the best behavior is, and when to present the typed input as a suggestion - it isn't always present in Apple's keyboards either, and probably for a reason.

**Comment by dylanhand** [comment]
This is fixed to not show the same suggestion twice.

Regarding when to present the typed input as a suggestion: this appears to happen in all cases when there is in fact input. On the other hand, if the user has just pressed the spacebar and not input any characters, the native keyboard attempts to suggest the next word based on context.

I assume this is more than we're capable of at the moment. Let me know if you notice any other situations in which typed input is *not* presented as an option and we can discuss how to handle it :)
