### ISSUE TITLE
Not all of the keyboard is updated when switching between light and dark mode

### ISSUE THREAD

**Issue by snomos** [divvun/giellakbd-ios#86]
Some (like the background), but not all, of the graphical elements of the keyboard are updated correctly when the system switches form dark to light mode (or back), if the keyboard is active in an app when the switch happens. It looks as follows in the Messages app:

Initial state, light mode:
![IMG_7745](https://user-images.githubusercontent.com/1255285/72662525-fabf5980-39f0-11ea-90e9-26b6cd2c5915.jpeg)

While app and keyboard is open, switching to dark mode - background changes, but not keys and suggestion dividers:
![IMG_7746](https://user-images.githubusercontent.com/1255285/72662540-23475380-39f1-11ea-88f4-77c079e3740e.jpeg)

After a forced-close and app restart, things are ok again (still dark mode):
![IMG_7747](https://user-images.githubusercontent.com/1255285/72662553-4114b880-39f1-11ea-85c0-9a620ac1718a.jpeg)

Now, switching back to light mode with the app & keyboard open, the same happens - the background switches, but not the keys (key colour and font colour), and not the suggestion dividers:
![IMG_7748](https://user-images.githubusercontent.com/1255285/72662633-01020580-39f2-11ea-855d-62f3de676872.jpeg)

Given that the background colour is changing, I assume it should be possible to get everything to change without having to restart the app.

This is the latest build, using the smn (Inari Sámi) keyboard.

**Comment by dylanhand** [comment]
Hi @snomos - I'm unable to reproduce this. What version of iOS are you running? Any special things that might have caused this?

Here's a screen recording of going from light to dark mode on my device, which works (works going dark->light as well)

![ezgif com-optimize](https://user-images.githubusercontent.com/431529/72710217-e1401e00-3b66-11ea-8b58-3af1cfce8898.gif)

Device: iPhone 11 Pro
iOS: 13.3

**Comment by dylanhand** [comment]
Just saw your note about using the smn keyboard. Will try with that (though it shouldn't make a difference).

**Comment by dylanhand** [comment]
Just re-tested with the smn keyboard and it also works as expected for me.

**Comment by snomos** [comment]
It seems to be triggered only when switching between light and dark mode using the Control Center. I have a video showing it, will try to upload it.

**Comment by dylanhand** [comment]
Ok, will try triggering from Control Center.

**Comment by snomos** [comment]
![RPReplay_Final1579509300](https://user-images.githubusercontent.com/1255285/72712375-937de280-3b73-11ea-9980-a76b47cec500.gif)

**Comment by dylanhand** [comment]
That did it.

I'll see if there's a simple way to fix this, but I think this might be an edge case. I see that Google's keyboard also doesn't update when switching modes. Ours (and Google's) does still update if you go back and return to the view.
