### ISSUE TITLE
First letter in long-press list

### ISSUE THREAD

**Issue by snomos** [divvun/giellakbd-ios#9]
Apple includes the unaccented letter as the first letter in the long-press list, we don't. It makes it easy to regret the accent/long-press, so it should be included.

**Comment by bbqsrc** [comment]
Still isn't in the rewrite, and also highlighting doesn't inherently select the first item in the list right now.

**Comment by dylanhand** [comment]
The native long press behavior differs on iPhone and iPad: 

**iPhone**: the selected key (e.g. 'a') appears as the first option in the popup and is selected by default.

**iPad**: the popup does not contain the selected key (e.g. 'a'), but no selection is made by default in the popup. If the user lets go before moving their finger up to the popup, the selected key ('a') will be used.

**Comment by snomos** [comment]
The native behavior is what we would like to reproduce, mainly because that is what users expect.

**Comment by dylanhand** [comment]
Hi @snomos - nice to virtually meet you.

I plan on duplicating the native behavior - I just added this note to remind myself what the native behavior is when I implement this feature :)

**Comment by snomos** [comment]
Hi @dylanhand - nice to meet you as well. Thanks for keeping me up-to-date 👍

**Comment by dylanhand** [comment]
To-do:
- [x] Show original letter on iPhone (show 'a' for instance in the a long-press menu)
- [ ] Shrink touch bounds on iPad so a character is only selected if the user's finger is actually touching the character. If out of bounds, the original character should be used.
- [ ] Make note about 'i' already existing in long-press options.

**Comment by dylanhand** [comment]
@bbqsrc FYI - when doing a long press, the 'i' character lists 'i' as an option, unlike other characters which only show accented variations of the selected character. Writing this note in case that's not intentional.

I've coded around it by only showing the default letter (eg. 'a') if it doesn't already exist in the list of long press letters.
