### ISSUE TITLE
layout issue on the overlay of the first key from the right on top row

### ISSUE THREAD

**Issue by waelsaad** [divvun/giellakbd-ios#96]
Hi, In the latest update, there seems to be a layout issue on the top row when pressing the first key from the right. Thanks

**Comment by dylanhand** [comment]
@waelsaad good eye. This appears to affect all keys touching the right side of the screen and all longpress overlays that are on the right half of the screen.

![Simulator Screen Shot - iPhone 11 Pro - 2020-01-24 at 10 13 47](https://user-images.githubusercontent.com/431529/73057605-3b582080-3e92-11ea-86f0-b3694b50e770.png)
![Simulator Screen Shot - iPhone 11 Pro - 2020-01-24 at 10 11 12](https://user-images.githubusercontent.com/431529/73057638-5460d180-3e92-11ea-9545-18a02ed0f776.png)

Note no connection to the 'i' letter.
![Simulator Screen Shot - iPhone 11 Pro - 2020-01-24 at 10 11 29](https://user-images.githubusercontent.com/431529/73057649-59258580-3e92-11ea-9be1-d607a39b58c6.png)
![Simulator Screen Shot - iPhone 11 Pro - 2020-01-24 at 10 11 34](https://user-images.githubusercontent.com/431529/73057658-5d51a300-3e92-11ea-8d94-b22ef3a8143e.png)

This one was triggered from the 'n' at the bottom.
![Simulator Screen Shot - iPhone 11 Pro - 2020-01-24 at 10 12 19](https://user-images.githubusercontent.com/431529/73057685-6b9fbf00-3e92-11ea-9bc3-09ff7874f0c3.png)

**Comment by waelsaad** [comment]
Yes that's right I noticed the same thing after I posted the issue, FYI, this bug is not happening in a prevoius version which I have downloaded just couple of days ago.

**Comment by waelsaad** [comment]
This one is important to be fixed :]

**Comment by snomos** [comment]
yup, and it is being worked on as we write 😄 

Should be fixed soon.

**Comment by waelsaad** [comment]
Thank you @dylanhand awsome work.
