### ISSUE TITLE
Where can I remove that subtitle text "Northern Sami" please? Its driving me crazy :)

### ISSUE THREAD

**Issue by waelsaad** [divvun/giellakbd-ios#97]
![Simulator Screen Shot - iPhone 11 Pro Max - 2020-01-24 at 14 31 16](https://user-images.githubusercontent.com/4057766/73042719-55a3f580-3eb6-11ea-99cb-04b50c81dc80.png)

**Comment by waelsaad** [comment]
I think you can't right, its the language type it appears there by default is that correct?

**Comment by dylanhand** [comment]
I don't believe that can be disabled. All third-party keyboards we've installed have a similar subtitle:

![IMG_0036](https://user-images.githubusercontent.com/431529/73058031-0d271080-3e93-11ea-9ba9-6aa1b5f261d6.PNG)

**Comment by snomos** [comment]
It can't be disabled, but it can be changed. It is controlled by the language code of the keyboard.
