### ISSUE TITLE
Is it possible in the future to breakup the KeyboardDefinitions.json into multiple .json files please?

### ISSUE THREAD

**Issue by waelsaad** [divvun/giellakbd-ios#98]
Hi :), one probablly last request, I understand all these features take time to implement and we are all busy with many things.

I am only suggesting if someone has time to break up the KeyboardDefinitions.json into multiple .json files for example based on devices and an additional one for common if required, it would be easier to follow and maintain the alphabets in this huge file.

I really think as of now this is probablly the best library I came across for a custom keyboard (even with the BannerView :]) and it would be good to keep building up on it.

Thanks

Wael

**Comment by snomos** [comment]
We don't write those json files :)

What we do is we write quite simple and straightforward yaml files, that are converted to json or whatever needed by https://github.com/divvun/kbdgen. Kbdgen also builds the iOS app (and Android app, and keyboards for Windows, macOS, Linux/Unix and ChromeOS).

I would suggest using kbdgen to build the keyboards, a lot of work has been put into making it do all the heavy lifting. Using kbdgen, any person can define a keyboard layout for their language 😄

**Comment by snomos** [comment]
Kbdgen is in the midst of a rewrite that should be done soon. For examples of what the yaml files look like, you can check https://github.com/giellalt/keyboard-sme/blob/master/sme.kbdgen/layouts/se-NO.yaml (desktop) or https://github.com/giellalt/keyboard-smi/blob/master/smi.kbdgen/layouts/se.yaml (mobile).

**Comment by snomos** [comment]
Also, our iOS and Android keyboard apps, which are presently targeted at the Sámi languages, will be generalised sometime this spring to be open to all languages. At that point you will be welcome to add your language to the app, in which case you can focus entirely on the letter layout & design, all the rest is done by our build system and delivered to the users.

**Comment by waelsaad** [comment]
Hi @snomos , I see, thank you for claryfing and sharing the info.. I look forward to your release. :)
